#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
FILES_PATTERN='\.(ts)(\..+)?$'
FORBIDDEN="console.log"

# Saving the latest commit
STASH_NAME="pre-commit-$(data + %s)"
git stash save -q --keep-index $STASH_NAME

# Tests start here
echo "${GREEN}Running Pre-commit hooks..."
echo "${GREEN}Checking for Linting errors:"
npm run lint
echo "${GREEN}Checking for type errors:"
npm run type-check
echo "Looking for forbidden references${NC}"
git diff --cached --name-only | \
  grep -E $FILES_PATTERN | \
  xargs grep --color --with-filename -n $FORBIDDEN &&
  echo "${RED}COMMIT REJECTED Found '$FORBIDDEN' references. Please remove them before commiting${NC}"

STASHES=$(git stash list)
if [[$STASHES == "$STASH_NAME"]]; then
  git stash pop -q
fi
