#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
FILES_PATTERN='\.(ts)(\..+)?$'
FORBIDDEN="console.log"

## Saving the unstaged changes
git stash save -q --keep-index "current wd"

## Tests start here
echo "${GREEN}Checking for Linting errors:${NC}"
npm run lint
echo "${GREEN}Checking for type errors:${NC}"
npm run type-check
echo "${GREEN}Looking for forbidden references${NC}"
git diff --cached --name-only | \
  grep -E $FILES_PATTERN | \
  xargs grep --color --with-filename -n $FORBIDDEN &&
  echo "${RED}COMMIT REJECTED Found '$FORBIDDEN' references. Please remove them before commiting${NC}"

$RESULT=$?
if [ $RESULT -ne 0 ]; then
	git stash save -q "original index"
	git stash apply -q --index stash@{1}
	git stash drop -q; git stash drop -q 
fi

[ $RESULT -ne 0 ] && exit 1

## Stage files changed or updated by tests 
git add -u
