#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
FILES_PATTERN='\.(ts)(\..+)?$'
FORBIDDEN="console.log"

# Saving the latest commit
STASH_NAME="pre-commit-$(date +%s)"
git stash save -q --keep-index $STASH_NAME

# Tests start here
echo "Running Pre-commit hooks${GREEN}..."
echo "Checking for Linting errors:${NC}"
npm run lint
echo "${GREEN}Checking for type errors:${NC}"
npm run type-check
echo "${GREEN}Looking for forbidden references${NC}"
git diff --cached --name-only | \
  grep -E $FILES_PATTERN | \
  xargs grep --color --with-filename -n $FORBIDDEN &&
  echo "${RED}COMMIT REJECTED Found '$FORBIDDEN' references. Please remove them before commiting${NC}"

STASHES=$(git stash list)
if [[ $STASHES == "$STASH_NAME"]]; then
  git stash pop -q
fi
