#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

## Saving the unstaged changes
git stash save -q --keep-index "current wd"

## Run script file with tests
test_result=1
./Scripts/run_tests.sh
test_result=$?

if [ $test_result -ne 0 ];then
  git stash save -q "original index"
  git stash apply -q --index stash@{1}
  git stash drop -q; git stash drop -q
  exit 1
fi

git add -u
