#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

## Saving the unstaged changes
git stash save -q --keep-index 

## Run script file with tests
test_result=1
./Scripts/run_tests.sh
test_result=$?

git stash pop -q 
echo "RESULT: $test_result"

[ $test_result -ne 0 ] && exit 1
exit 0
